# #a Test case 1 
# print("\(^o^) Selamat datang di Kalkulator Sederhana (^o^)/")
# print("Ketik 1 untuk menghitung penjumlahan.")
# print("Ketik 2 untuk menghitung pengurangan.")
# print("Ketik 3 untuk menghitung perkalian.")
# print("Ketik 4 untuk menghitung pembagian.")
# print("Ketik 5 untuk menghitung sisa hasil bagi(modulus).")
# print("Ketik 6 untuk menghitung pemangkaran.")
# pilihan_anda = int(input("Masukkan pilihan Anda: "))
# bilangan = int(input("Masukkan bilangan pertama: "))
# bilangan2 = int(input("Masukkan bilangan kedua: "))
# rumusnya = (bilangan + bilangan2)
# print("Hasil dari", bilangan, "di jumlahkan dengan", bilangan2, "adalah", rumusnya)

#b Test case 2
# print("\(^o^) Selamat datang di Kalkulator Sederhana (^o^)/")
# print("Ketik 1 untuk menghitung penjumlahan.")
# print("Ketik 2 untuk menghitung pengurangan.")
# print("Ketik 3 untuk menghitung perkalian.")
# print("Ketik 4 untuk menghitung pembagian.")
# print("Ketik 5 untuk menghitung sisa hasil bagi(modulus).")
# print("Ketik 6 untuk menghitung pemangkaran.")
# pilihan_anda = int(input("Masukkan pilihan Anda: "))
# bilangan = int(input("Masukkan bilangan pertama: "))
# bilangan2 = int(input("Masukkan bilangan kedua: "))
# rumusnya = (bilangan - bilangan2)
# print("Hasil dari", bilangan, "dikurangkan dengan", bilangan2, "adalah", rumusnya)

#c Test case 3 
# print("\(^o^) Selamat datang di Kalkulator Sederhana (^o^)/")
# print("Ketik 1 untuk menghitung penjumlahan.")
# print("Ketik 2 untuk menghitung pengurangan.")
# print("Ketik 3 untuk menghitung perkalian.")
# print("Ketik 4 untuk menghitung pembagian.")
# print("Ketik 5 untuk menghitung sisa hasil bagi(modulus).")
# print("Ketik 6 untuk menghitung pemangkaran.")
# pilihan_anda = int(input("Masukkan pilihan Anda: "))
# bilangan = int(input("Masukkan bilangan pertama: "))
# bilangan2 = int(input("Masukkan bilangan kedua: "))
# rumusnya = (bilangan * bilangan2)
# print("Hasil dari", bilangan, "dikalikan dengan", bilangan2, "adalah", rumusnya)

#d Test Case 4
# print("\(^o^) Selamat datang di Kalkulator Sederhana (^o^)/")
# print("Ketik 1 untuk menghitung penjumlahan.")
# print("Ketik 2 untuk menghitung pengurangan.")
# print("Ketik 3 untuk menghitung perkalian.")
# print("Ketik 4 untuk menghitung pembagian.")
# print("Ketik 5 untuk menghitung sisa hasil bagi(modulus).")
# print("Ketik 6 untuk menghitung pemangkaran.")
# pilihan_anda = int(input("Masukkan pilihan Anda: "))
# bilangan = int(input("Masukkan bilangan pertama: "))
# bilangan2 = int(input("Masukkan bilangan kedua: "))
# rumusnya = (bilangan / bilangan2)
# print("Hasil dari", bilangan, "dibagi dengan", bilangan2, "adalah", rumusnya)

#e Test case 5
# print("\(^o^) Selamat datang di Kalkulator Sederhana (^o^)/")
# print("Ketik 1 untuk menghitung penjumlahan.")
# print("Ketik 2 untuk menghitung pengurangan.")
# print("Ketik 3 untuk menghitung perkalian.")
# print("Ketik 4 untuk menghitung pembagian.")
# print("Ketik 5 untuk menghitung sisa hasil bagi(modulus).")
# print("Ketik 6 untuk menghitung pemangkaran.")
# pilihan_anda = int(input("Masukkan pilihan Anda: "))
# bilangan = int(input("Masukkan bilangan pertama: "))
# bilangan2 = int(input("Masukkan bilangan kedua: "))
# rumusnya = (bilangan % bilangan2)
# print("Hasil dari", bilangan, "dimodulus dengan", bilangan2, "adalah", rumusnya)

#f Test case 6 
print("\(^o^) Selamat datang di Kalkulator Sederhana (^o^)/")
print("Ketik 1 untuk menghitung penjumlahan.")
print("Ketik 2 untuk menghitung pengurangan.")
print("Ketik 3 untuk menghitung perkalian.")
print("Ketik 4 untuk menghitung pembagian.")
print("Ketik 5 untuk menghitung sisa hasil bagi(modulus).")
print("Ketik 6 untuk menghitung pemangkaran.")
pilihan_anda = int(input("Masukkan pilihan Anda: "))
bilangan = int(input("Masukkan bilangan pertama: "))
bilangan2 = int(input("Masukkan bilangan kedua: "))
rumusnya = (bilangan ** bilangan2)
print("Hasil dari", bilangan, "dipangkatkan dengan", bilangan2, "adalah", rumusnya)